apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: jool-docker
  labels:
    jira-key: JSC
    language: Dockerfile
  annotations:
    github.com/project-slug: 'wandera/jool-docker'
    backstage.io/techdocs-ref: dir:.
    sonarqube.org/project-key: com.wandera.zircon:jool-docker
spec:
  type: tooling
  lifecycle: production
  owner: zircon
  system: Connect
  description: Docker image for jool
